# Generated by Django 3.2.3 on 2021-08-17 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.IntegerField()),
                ('name', models.CharField(max_length=64)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=7)),
            ],
            options={
                'ordering': ['no'],
            },
        ),
    ]
